import type { CatalogItem } from "./types";

const allergens = "unknown" as const;

/** List prices we set, in USD cents. Every drink still needs a temperature at order time. */
export const COFFEE_ITEMS: readonly CatalogItem[] = [
  {
    id: "coffee-01",
    machineId: "coffee",
    name: "Americano",
    nameBasis: "photo",
    summary: "Dark coffee in a white cup with a black lid.",
    photoNote: "Black coffee and a ring of crema are visible. No ingredient list.",
    priceCents: 280,
    imagePath: "images/coffee/coffee-01.webp",
    tasteTags: ["plain", "strong", "bitter"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
  {
    id: "coffee-02",
    machineId: "coffee",
    name: "Cocoa Cappuccino",
    nameBasis: "photo",
    summary: "Foamy coffee topped with a dusting of brown powder.",
    photoNote: "Foam and a cocoa-colored dusting are visible. No ingredient list.",
    priceCents: 380,
    imagePath: "images/coffee/coffee-02.webp",
    tasteTags: ["creamy", "sweet", "mild"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-03",
    machineId: "coffee",
    name: "Vanilla Latte",
    nameBasis: "photo",
    summary: "Latte with a leaf poured into the foam. Vanilla is pictured beside the cup.",
    photoNote: "A vanilla flower and vanilla pods are props beside the cup. No ingredient list.",
    priceCents: 420,
    imagePath: "images/coffee/coffee-03.webp",
    tasteTags: ["sweet", "creamy", "mild"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
  {
    id: "coffee-04",
    machineId: "coffee",
    name: "Latte",
    nameBasis: "photo",
    summary: "Coffee and milk with a heart poured into the foam.",
    photoNote: "Latte art is visible. No flavor props and no ingredient list.",
    priceCents: 360,
    imagePath: "images/coffee/coffee-04.webp",
    tasteTags: ["creamy", "mild"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
  {
    id: "coffee-05",
    machineId: "coffee",
    name: "Daily Black",
    nameBasis: "photo",
    summary: "Dark coffee in a white cup with a black lid.",
    photoNote:
      "Looks much like the Americano. The photo shows black coffee only, with no ingredient list. Keep the two as separate items and show this image.",
    priceCents: 260,
    imagePath: "images/coffee/coffee-05.webp",
    tasteTags: ["plain", "strong", "bitter"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-06",
    machineId: "coffee",
    name: "Mocha",
    nameBasis: "photo",
    summary: "Brown drink under a cocoa-colored dusting. Chocolate is pictured beside the cup.",
    photoNote: "Chocolate pieces and cocoa powder sit beside the cup. No ingredient list.",
    priceCents: 440,
    imagePath: "images/coffee/coffee-06.webp",
    tasteTags: ["sweet", "chocolate", "rich"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-07",
    machineId: "coffee",
    name: "Spiced Chai",
    nameBasis: "photo",
    summary: "Pale spiced drink. Cinnamon, ginger, and cardamom are pictured beside the cup.",
    photoNote: "Whole spices are props. No ingredient list.",
    priceCents: 370,
    imagePath: "images/coffee/coffee-07.webp",
    tasteTags: ["spiced", "sweet", "creamy"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-08",
    machineId: "coffee",
    name: "Caramel Cream",
    nameBasis: "photo",
    summary: "Whipped cream with an amber drizzle in a crosshatch.",
    photoNote: "Cream and a caramel-colored sauce are visible on top. No ingredient list.",
    priceCents: 460,
    imagePath: "images/coffee/coffee-08.webp",
    tasteTags: ["sweet", "rich", "creamy"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
  {
    id: "coffee-09",
    machineId: "coffee",
    name: "Matcha",
    nameBasis: "photo",
    summary: "Bright green drink in a white cup.",
    photoNote: "The liquid is green and has no foam art. No ingredient list. This is not the matcha latte.",
    priceCents: 400,
    imagePath: "images/coffee/coffee-09.webp",
    tasteTags: ["mild", "light"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
  {
    id: "coffee-10",
    machineId: "coffee",
    name: "Berry Cup",
    nameBasis: "photo",
    summary: "Deep red drink in a clear cup. Mixed berries are pictured beside it.",
    photoNote: "Berries are props. No ingredient list. Still served hot, iced, or at room temperature.",
    priceCents: 390,
    imagePath: "images/coffee/coffee-10.webp",
    tasteTags: ["fruity", "sweet"],
    allergens,
    requiresTemperature: true,
    suits: ["iced"],
  },
  {
    id: "coffee-11",
    machineId: "coffee",
    name: "Mango Cup",
    nameBasis: "photo",
    summary: "Thick yellow-orange drink. Mango is pictured beside the cup.",
    photoNote: "Cut mango is a prop. No ingredient list.",
    priceCents: 390,
    imagePath: "images/coffee/coffee-11.webp",
    tasteTags: ["fruity", "sweet"],
    allergens,
    requiresTemperature: true,
    suits: ["iced"],
  },
  {
    id: "coffee-12",
    machineId: "coffee",
    name: "Orange Cup",
    nameBasis: "photo",
    summary: "Orange drink in a clear cup. An orange is pictured beside it.",
    photoNote: "A whole orange and a slice are props. No ingredient list.",
    priceCents: 340,
    imagePath: "images/coffee/coffee-12.webp",
    tasteTags: ["fruity", "tart"],
    allergens,
    requiresTemperature: true,
    suits: ["iced", "room"],
  },
  {
    id: "coffee-13",
    machineId: "coffee",
    name: "Lemon Tea",
    nameBasis: "photo",
    summary: "Amber tea with lemon slices in the cup. Tea leaves are pictured beside it.",
    photoNote: "Lemon and loose tea are visible. No ingredient list.",
    priceCents: 320,
    imagePath: "images/coffee/coffee-13.webp",
    tasteTags: ["tart", "light"],
    allergens,
    requiresTemperature: true,
    suits: ["iced", "hot"],
  },
  {
    id: "coffee-14",
    machineId: "coffee",
    name: "Mocha Whip",
    nameBasis: "photo",
    summary: "Whipped cream piled up and finished with chocolate shavings.",
    photoNote: "Cream and chocolate shavings are on top. No ingredient list. This is not the mocha.",
    priceCents: 480,
    imagePath: "images/coffee/coffee-14.webp",
    tasteTags: ["sweet", "chocolate", "rich"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-15",
    machineId: "coffee",
    name: "Covered Cup",
    nameBasis: "contents-hidden",
    summary: "A lidded white cup. The drink is not visible.",
    photoNote:
      "The lid is closed and there are no props. Do not guess the drink, the flavor, or the ingredients. Allergens are unknown.",
    priceCents: 300,
    imagePath: "images/coffee/coffee-15.webp",
    tasteTags: [],
    allergens,
    requiresTemperature: true,
    suits: [],
  },
  {
    id: "coffee-16",
    machineId: "coffee",
    name: "Black Tea",
    nameBasis: "photo",
    summary: "Amber tea. Tea leaves are pictured beside the cup.",
    photoNote: "Steam and loose tea are visible. No lemon and no ingredient list. This is not the lemon tea.",
    priceCents: 250,
    imagePath: "images/coffee/coffee-16.webp",
    tasteTags: ["plain", "light"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-17",
    machineId: "coffee",
    name: "Espresso",
    nameBasis: "photo",
    summary: "Short coffee with a thick crema, in a white cup with a black lid.",
    photoNote: "Golden crema is visible. No ingredient list. This is not the Americano or the Daily Black.",
    priceCents: 240,
    imagePath: "images/coffee/coffee-17.webp",
    tasteTags: ["strong", "bitter"],
    allergens,
    requiresTemperature: true,
    suits: ["hot"],
  },
  {
    id: "coffee-18",
    machineId: "coffee",
    name: "Matcha Latte",
    nameBasis: "photo",
    summary: "Green drink with a heart poured into the foam, in a green cup.",
    photoNote: "Foam art is visible. No ingredient list. This is not the plain matcha.",
    priceCents: 450,
    imagePath: "images/coffee/coffee-18.webp",
    tasteTags: ["creamy", "mild"],
    allergens,
    requiresTemperature: true,
    suits: ["hot", "iced"],
  },
];
