import type { CatalogItem } from "./types";

const allergens = "unknown" as const;

/** List prices we set, in USD cents. A snack line is complete without a temperature. */
export const SNACK_ITEMS: readonly CatalogItem[] = [
  {
    id: "snacks-01",
    machineId: "snacks",
    name: "Cinnamon Almonds",
    nameBasis: "photo",
    summary: "A bag of roasted almonds with cinnamon sticks on the pack.",
    photoNote: "The pieces look like almonds. No printed ingredient list, so allergens stay unknown.",
    priceCents: 320,
    imagePath: "images/snacks/snacks-01.webp",
    tasteTags: ["sweet", "nutty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-02",
    machineId: "snacks",
    name: "Citrus Berry Drops",
    nameBasis: "photo",
    summary: "Sugar-coated yellow and pink gummy drops. Lemon and strawberry are on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-02.webp",
    tasteTags: ["sweet", "fruity", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-03",
    machineId: "snacks",
    name: "Fruit Slice Gummies",
    nameBasis: "photo",
    summary: "Gummies shaped like fruit slices. Strawberry, orange, and pineapple are on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-03.webp",
    tasteTags: ["sweet", "fruity", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-04",
    machineId: "snacks",
    name: "Nut Crunch Bar",
    nameBasis: "photo",
    summary: "An oat bar with peanuts and chocolate pieces showing in the cut face.",
    photoNote: "Peanuts and chocolate are visible in the bar. No printed ingredient list, so allergens stay unknown.",
    priceCents: 280,
    imagePath: "images/snacks/snacks-04.webp",
    tasteTags: ["sweet", "nutty", "crunchy", "chocolate"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-05",
    machineId: "snacks",
    name: "Salted Peanuts",
    nameBasis: "photo",
    summary: "A clear window of roasted peanuts, with salt on the pieces in front.",
    photoNote: "The pieces look like peanuts. No printed ingredient list, so allergens stay unknown.",
    priceCents: 220,
    imagePath: "images/snacks/snacks-05.webp",
    tasteTags: ["salty", "nutty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-06",
    machineId: "snacks",
    name: "Peanut Butter Cups",
    nameBasis: "photo",
    summary: "Chocolate cups with a tan center. Peanuts are pictured beside the pack.",
    photoNote: "A cut cup shows a tan filling. No printed ingredient list, so allergens stay unknown.",
    priceCents: 250,
    imagePath: "images/snacks/snacks-06.webp",
    tasteTags: ["sweet", "chocolate", "nutty"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-07",
    machineId: "snacks",
    name: "Green Onion Chips",
    nameBasis: "photo",
    summary: "A tube of thin chips. Green onion and a white dip are on the label.",
    photoNote: "No printed ingredient list.",
    priceCents: 280,
    imagePath: "images/snacks/snacks-07.webp",
    tasteTags: ["savory", "salty", "crispy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-08",
    machineId: "snacks",
    name: "Fruit Gummy Bears",
    nameBasis: "photo",
    summary: "Bear-shaped gummies. Fruit is printed on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-08.webp",
    tasteTags: ["sweet", "fruity", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-09",
    machineId: "snacks",
    name: "Trail Mix",
    nameBasis: "photo",
    summary: "A mix of nuts, raisins, and candy-coated chocolates.",
    photoNote: "Almonds, peanuts, raisins, and coated chocolates are visible. No printed ingredient list, so allergens stay unknown.",
    priceCents: 300,
    imagePath: "images/snacks/snacks-09.webp",
    tasteTags: ["sweet", "salty", "nutty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-10",
    machineId: "snacks",
    name: "Cheese Tortilla Chips",
    nameBasis: "photo",
    summary: "Triangle chips. Cheese sauce is pictured on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 240,
    imagePath: "images/snacks/snacks-10.webp",
    tasteTags: ["savory", "salty", "crispy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-11",
    machineId: "snacks",
    name: "Chocolate Chip Cookies",
    nameBasis: "photo",
    summary: "Cookies with dark chips, loose in front of the bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 220,
    imagePath: "images/snacks/snacks-11.webp",
    tasteTags: ["sweet", "chocolate", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-12",
    machineId: "snacks",
    name: "Cream Sandwich Cookies",
    nameBasis: "photo",
    summary: "Dark cookies with a white filling.",
    photoNote: "A broken cookie shows the white center. No printed ingredient list.",
    priceCents: 200,
    imagePath: "images/snacks/snacks-12.webp",
    tasteTags: ["sweet", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-13",
    machineId: "snacks",
    name: "Cheese Crackers",
    nameBasis: "photo",
    summary: "Small square crackers. A cheese wedge is printed on the bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-13.webp",
    tasteTags: ["savory", "salty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-14",
    machineId: "snacks",
    name: "Peanut Caramel Bar",
    nameBasis: "photo",
    summary: "A chocolate bar with peanuts and a caramel-colored layer in the cut face.",
    photoNote: "Peanuts are visible in the bar and beside it. No printed ingredient list, so allergens stay unknown.",
    priceCents: 260,
    imagePath: "images/snacks/snacks-14.webp",
    tasteTags: ["sweet", "nutty", "chewy", "chocolate"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-15",
    machineId: "snacks",
    name: "Cheese Sandwich Crackers",
    nameBasis: "photo",
    summary: "Round crackers with an orange filling. Cheese is printed on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 200,
    imagePath: "images/snacks/snacks-15.webp",
    tasteTags: ["savory", "salty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-16",
    machineId: "snacks",
    name: "Cranberry Almond Bar",
    nameBasis: "photo",
    summary: "An oat bar with almonds and red dried fruit showing.",
    photoNote: "Almonds and cranberry-like fruit are visible. No printed ingredient list, so allergens stay unknown.",
    priceCents: 280,
    imagePath: "images/snacks/snacks-16.webp",
    tasteTags: ["sweet", "nutty", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-17",
    machineId: "snacks",
    name: "Beef Jerky",
    nameBasis: "photo",
    summary: "Dark dried meat strips. A cow silhouette is on the pouch.",
    photoNote: "The strips look like jerky. No printed ingredient list.",
    priceCents: 420,
    imagePath: "images/snacks/snacks-17.webp",
    tasteTags: ["savory", "salty", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-18",
    machineId: "snacks",
    name: "Crisp Rice Squares",
    nameBasis: "photo",
    summary: "Puffed cereal squares with white marshmallow pieces.",
    photoNote: "Marshmallows are pictured on the pack. No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-18.webp",
    tasteTags: ["sweet", "crispy", "light"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-19",
    machineId: "snacks",
    name: "Potato Chips",
    nameBasis: "photo",
    summary: "Plain ridged chips. A potato is printed on the yellow bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 200,
    imagePath: "images/snacks/snacks-19.webp",
    tasteTags: ["salty", "crispy", "plain"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-20",
    machineId: "snacks",
    name: "Caramel Oat Bar",
    nameBasis: "photo",
    summary: "An oat bar with a caramel-colored layer, chocolate drizzle, and chocolate chunks.",
    photoNote: "Caramel-colored cubes and chocolate are beside the bar. No printed ingredient list.",
    priceCents: 270,
    imagePath: "images/snacks/snacks-20.webp",
    tasteTags: ["sweet", "chewy", "chocolate", "rich"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-21",
    machineId: "snacks",
    name: "Cookies and Cream Bar",
    nameBasis: "photo",
    summary: "A white bar packed with dark cookie pieces. Sandwich cookies are on the wrapper.",
    photoNote: "The cut face shows cookie crumbs. No printed ingredient list.",
    priceCents: 240,
    imagePath: "images/snacks/snacks-21.webp",
    tasteTags: ["sweet", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-22",
    machineId: "snacks",
    name: "Pretzels",
    nameBasis: "photo",
    summary: "Salted twisted pretzels in a blue bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-22.webp",
    tasteTags: ["salty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-23",
    machineId: "snacks",
    name: "Fruit Chews",
    nameBasis: "photo",
    summary: "Soft square fruit chews. Strawberry, orange, and grapes are on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 160,
    imagePath: "images/snacks/snacks-23.webp",
    tasteTags: ["sweet", "fruity", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-24",
    machineId: "snacks",
    name: "Chili Lime Rolls",
    nameBasis: "photo",
    summary: "Rolled chips dusted red. Chili and lime are on the pack.",
    photoNote: "No printed ingredient list.",
    priceCents: 220,
    imagePath: "images/snacks/snacks-24.webp",
    tasteTags: ["spicy", "salty", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-25",
    machineId: "snacks",
    name: "Date Nut Bar",
    nameBasis: "photo",
    summary: "A dense bar. Dates, almonds, walnuts, and a boiled egg are pictured with it.",
    photoNote: "Dates and nuts are visible in the bar and beside it. No printed ingredient list, so allergens stay unknown.",
    priceCents: 300,
    imagePath: "images/snacks/snacks-25.webp",
    tasteTags: ["sweet", "nutty", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-26",
    machineId: "snacks",
    name: "Hot Cheese Curls",
    nameBasis: "photo",
    summary: "Red cheese curls. Flames and a cheese wedge are on the bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 220,
    imagePath: "images/snacks/snacks-26.webp",
    tasteTags: ["spicy", "savory", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-27",
    machineId: "snacks",
    name: "Chocolate Peanuts",
    nameBasis: "photo",
    summary: "Chocolate-coated ovals. A cut piece shows a peanut center.",
    photoNote: "A peanut center is visible. No printed ingredient list, so allergens stay unknown.",
    priceCents: 250,
    imagePath: "images/snacks/snacks-27.webp",
    tasteTags: ["sweet", "chocolate", "nutty"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-28",
    machineId: "snacks",
    name: "Oat Cranberry Bar",
    nameBasis: "photo",
    summary: "An oat bar with red dried fruit. Oats are printed on the wrapper.",
    photoNote: "No nuts are obvious in this photo. No printed ingredient list, so allergens stay unknown.",
    priceCents: 240,
    imagePath: "images/snacks/snacks-28.webp",
    tasteTags: ["sweet", "chewy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-29",
    machineId: "snacks",
    name: "Wafer Bar",
    nameBasis: "photo",
    summary: "A chocolate-coated bar with crisp wafer layers in the cut face.",
    photoNote: "No printed ingredient list.",
    priceCents: 220,
    imagePath: "images/snacks/snacks-29.webp",
    tasteTags: ["sweet", "chocolate", "crunchy"],
    allergens,
    requiresTemperature: false,
  },
  {
    id: "snacks-30",
    machineId: "snacks",
    name: "Popcorn",
    nameBasis: "photo",
    summary: "Plain popped corn in a blue and white bag.",
    photoNote: "No printed ingredient list.",
    priceCents: 180,
    imagePath: "images/snacks/snacks-30.webp",
    tasteTags: ["salty", "light", "crispy"],
    allergens,
    requiresTemperature: false,
  },
];
